/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "HorusBinaryV3"
 * 	found in "../HorusBinaryV3.asn1"
 * 	`asn1c -no-gen-OER -no-gen-example`
 */

#ifndef	_AdditionalSensorType_H_
#define	_AdditionalSensorType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <IA5String.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CustomFieldValues;

/* AdditionalSensorType */
typedef struct AdditionalSensorType {
	IA5String_t	*name	/* OPTIONAL */;
	struct CustomFieldValues	*values	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AdditionalSensorType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AdditionalSensorType;
extern asn_SEQUENCE_specifics_t asn_SPC_AdditionalSensorType_specs_1;
extern asn_TYPE_member_t asn_MBR_AdditionalSensorType_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CustomFieldValues.h"

#endif	/* _AdditionalSensorType_H_ */
#include <asn_internal.h>
