/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "HorusBinaryV3"
 * 	found in "../HorusBinaryV3.asn1"
 * 	`asn1c -no-gen-OER -no-gen-example`
 */

#include "AdditionalSensorType.h"

static const int permitted_alphabet_table_2[256] = {
 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,	/*                  */
 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,	/*                  */
 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,	/*              -   */
 2, 3, 4, 5, 6, 7, 8, 9,10,11, 0, 0, 0, 0, 0, 0,	/* 0123456789       */
 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,	/*                  */
 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,	/*                  */
 0,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,	/*  abcdefghijklmno */
27,28,29,30,31,32,33,34,35,36,37, 0, 0, 0, 0, 0,	/* pqrstuvwxyz      */
};
static const int permitted_alphabet_code2value_2[37] = {
45,48,49,50,51,52,53,54,55,56,57,97,98,99,100,101,
102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,
118,119,120,121,122,};


static int check_permitted_alphabet_2(const void *sptr) {
	const int *table = permitted_alphabet_table_2;
	/* The underlying type is IA5String */
	const IA5String_t *st = (const IA5String_t *)sptr;
	const uint8_t *ch = st->buf;
	const uint8_t *end = ch + st->size;
	
	for(; ch < end; ch++) {
		uint8_t cv = *ch;
		if(!table[cv]) return -1;
	}
	return 0;
}

static int
memb_name_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const IA5String_t *st = (const IA5String_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size >= 1 && size <= 20)
		 && !check_permitted_alphabet_2(st)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int asn_PER_MAP_name_2_v2c(unsigned int value) {
	if(value >= sizeof(permitted_alphabet_table_2)/sizeof(permitted_alphabet_table_2[0]))
		return -1;
	return permitted_alphabet_table_2[value] - 1;
}
static int asn_PER_MAP_name_2_c2v(unsigned int code) {
	if(code >= sizeof(permitted_alphabet_code2value_2)/sizeof(permitted_alphabet_code2value_2[0]))
		return -1;
	return permitted_alphabet_code2value_2[code];
}
static asn_per_constraints_t asn_PER_memb_name_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 6,  6,  45,  122 }	/* (45..122) */,
	{ APC_CONSTRAINED,	 5,  5,  1,  20 }	/* (SIZE(1..20)) */,
	asn_PER_MAP_name_2_v2c,	/* Value to PER code map */
	asn_PER_MAP_name_2_c2v	/* PER code to value map */
};
asn_TYPE_member_t asn_MBR_AdditionalSensorType_1[] = {
	{ ATF_POINTER, 2, offsetof(struct AdditionalSensorType, name),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IA5String,
		0,
		{ 0, &asn_PER_memb_name_constr_2,  memb_name_constraint_1 },
		0, 0, /* No default value */
		"name"
		},
	{ ATF_POINTER, 1, offsetof(struct AdditionalSensorType, values),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_CustomFieldValues,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"values"
		},
};
static const int asn_MAP_AdditionalSensorType_oms_1[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_AdditionalSensorType_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_AdditionalSensorType_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* name */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* values */
};
asn_SEQUENCE_specifics_t asn_SPC_AdditionalSensorType_specs_1 = {
	sizeof(struct AdditionalSensorType),
	offsetof(struct AdditionalSensorType, _asn_ctx),
	asn_MAP_AdditionalSensorType_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_AdditionalSensorType_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_AdditionalSensorType = {
	"AdditionalSensorType",
	"AdditionalSensorType",
	&asn_OP_SEQUENCE,
	asn_DEF_AdditionalSensorType_tags_1,
	sizeof(asn_DEF_AdditionalSensorType_tags_1)
		/sizeof(asn_DEF_AdditionalSensorType_tags_1[0]), /* 1 */
	asn_DEF_AdditionalSensorType_tags_1,	/* Same as above */
	sizeof(asn_DEF_AdditionalSensorType_tags_1)
		/sizeof(asn_DEF_AdditionalSensorType_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_AdditionalSensorType_1,
	2,	/* Elements count */
	&asn_SPC_AdditionalSensorType_specs_1	/* Additional specs */
};

