/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "HorusBinaryV3"
 * 	found in "../HorusBinaryV3.asn1"
 * 	`asn1c -no-gen-example`
 */

#include "BitFlags.h"

asn_TYPE_member_t asn_MBR_BitFlags_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct BitFlags, b0),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"b0"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BitFlags, b1),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"b1"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BitFlags, b2),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"b2"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BitFlags, b3),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"b3"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BitFlags, b4),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"b4"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BitFlags, b5),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"b5"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BitFlags, b6),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"b6"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BitFlags, b7),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"b7"
		},
};
static const ber_tlv_tag_t asn_DEF_BitFlags_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_BitFlags_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* b0 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* b1 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* b2 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* b3 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* b4 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* b5 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* b6 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 } /* b7 */
};
asn_SEQUENCE_specifics_t asn_SPC_BitFlags_specs_1 = {
	sizeof(struct BitFlags),
	offsetof(struct BitFlags, _asn_ctx),
	asn_MAP_BitFlags_tag2el_1,
	8,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_BitFlags = {
	"BitFlags",
	"BitFlags",
	&asn_OP_SEQUENCE,
	asn_DEF_BitFlags_tags_1,
	sizeof(asn_DEF_BitFlags_tags_1)
		/sizeof(asn_DEF_BitFlags_tags_1[0]), /* 1 */
	asn_DEF_BitFlags_tags_1,	/* Same as above */
	sizeof(asn_DEF_BitFlags_tags_1)
		/sizeof(asn_DEF_BitFlags_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_BitFlags_1,
	8,	/* Elements count */
	&asn_SPC_BitFlags_specs_1	/* Additional specs */
};

