/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "HorusBinaryV3"
 * 	found in "../HorusBinaryV3.asn1"
 * 	`asn1c -no-gen-OER -no-gen-example`
 */

#ifndef	_BitFlags_H_
#define	_BitFlags_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* BitFlags */
typedef struct BitFlags {
	BOOLEAN_t	 b0;
	BOOLEAN_t	 b1;
	BOOLEAN_t	 b2;
	BOOLEAN_t	 b3;
	BOOLEAN_t	 b4;
	BOOLEAN_t	 b5;
	BOOLEAN_t	 b6;
	BOOLEAN_t	 b7;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BitFlags_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BitFlags;
extern asn_SEQUENCE_specifics_t asn_SPC_BitFlags_specs_1;
extern asn_TYPE_member_t asn_MBR_BitFlags_1[8];

#ifdef __cplusplus
}
#endif

#endif	/* _BitFlags_H_ */
#include <asn_internal.h>
