/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "HorusBinaryV3"
 * 	found in "../HorusBinaryV3.asn1"
 * 	`asn1c -no-gen-OER -no-gen-example`
 */

#ifndef	_CustomFieldValues_H_
#define	_CustomFieldValues_H_


#include <asn_application.h>

/* Including external dependencies */
#include <IA5String.h>
#include "BitFlags.h"
#include <NativeInteger.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <NativeReal.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CustomFieldValues_PR {
	CustomFieldValues_PR_NOTHING,	/* No components present */
	CustomFieldValues_PR_horusStr,
	CustomFieldValues_PR_horusInt,
	CustomFieldValues_PR_horusReal,
	CustomFieldValues_PR_horusBool
} CustomFieldValues_PR;

/* CustomFieldValues */
typedef struct CustomFieldValues {
	CustomFieldValues_PR present;
	union CustomFieldValues_u {
		IA5String_t	 horusStr;
		struct horusInt {
			A_SEQUENCE_OF(long) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} horusInt;
		struct horusReal {
			A_SEQUENCE_OF(double) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} horusReal;
		BitFlags_t	 horusBool;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CustomFieldValues_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CustomFieldValues;
extern asn_CHOICE_specifics_t asn_SPC_CustomFieldValues_specs_1;
extern asn_TYPE_member_t asn_MBR_CustomFieldValues_1[4];
extern asn_per_constraints_t asn_PER_type_CustomFieldValues_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _CustomFieldValues_H_ */
#include <asn_internal.h>
