/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "HorusBinaryV3"
 * 	found in "../HorusBinaryV3.asn1"
 * 	`asn1c -no-gen-example`
 */

#include "CustomFieldValues.h"

static const int permitted_alphabet_table_2[256] = {
 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,	/*                  */
 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,	/*                  */
 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 3, 4, 5,	/* .          + -./ */
 6, 7, 8, 9,10,11,12,13,14,15, 0, 0, 0,16, 0, 0,	/* 0123456789   =   */
 0,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,	/*  ABCDEFGHIJKLMNO */
32,33,34,35,36,37,38,39,40,41,42, 0, 0, 0, 0,43,	/* PQRSTUVWXYZ    _ */
 0,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,	/*  abcdefghijklmno */
59,60,61,62,63,64,65,66,67,68,69, 0, 0, 0, 0, 0,	/* pqrstuvwxyz      */
};
static const int permitted_alphabet_code2value_2[69] = {
32,43,45,46,47,48,49,50,51,52,53,54,55,56,57,61,
65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,
81,82,83,84,85,86,87,88,89,90,95,97,98,99,100,101,
102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,
118,119,120,121,122,};


static int check_permitted_alphabet_2(const void *sptr) {
	const int *table = permitted_alphabet_table_2;
	/* The underlying type is IA5String */
	const IA5String_t *st = (const IA5String_t *)sptr;
	const uint8_t *ch = st->buf;
	const uint8_t *end = ch + st->size;
	
	for(; ch < end; ch++) {
		uint8_t cv = *ch;
		if(!table[cv]) return -1;
	}
	return 0;
}

static int
memb_horusStr_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const IA5String_t *st = (const IA5String_t *)sptr;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(!check_permitted_alphabet_2(st)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int asn_PER_MAP_horusStr_2_v2c(unsigned int value) {
	if(value >= sizeof(permitted_alphabet_table_2)/sizeof(permitted_alphabet_table_2[0]))
		return -1;
	return permitted_alphabet_table_2[value] - 1;
}
static int asn_PER_MAP_horusStr_2_c2v(unsigned int code) {
	if(code >= sizeof(permitted_alphabet_code2value_2)/sizeof(permitted_alphabet_code2value_2[0]))
		return -1;
	return permitted_alphabet_code2value_2[code];
}
static int
memb_horusInt_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 4)) {
		/* Perform validation of the inner elements */
		return SEQUENCE_OF_constraint(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_horusReal_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 4)) {
		/* Perform validation of the inner elements */
		return SEQUENCE_OF_constraint(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_type_horusInt_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..4)) */};
static asn_per_constraints_t asn_PER_type_horusInt_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 2,  2,  1,  4 }	/* (SIZE(1..4)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_horusReal_constr_5 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..4)) */};
static asn_per_constraints_t asn_PER_type_horusReal_constr_5 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 2,  2,  1,  4 }	/* (SIZE(1..4)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_horusStr_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
static asn_per_constraints_t asn_PER_memb_horusStr_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 7,  7,  32,  122 }	/* (32..122) */,
	{ APC_SEMI_CONSTRAINED,	-1, -1,  0,  0 }	/* (SIZE(0..MAX)) */,
	asn_PER_MAP_horusStr_2_v2c,	/* Value to PER code map */
	asn_PER_MAP_horusStr_2_c2v	/* PER code to value map */
};
static asn_oer_constraints_t asn_OER_memb_horusInt_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..4)) */};
static asn_per_constraints_t asn_PER_memb_horusInt_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 2,  2,  1,  4 }	/* (SIZE(1..4)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_horusReal_constr_5 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..4)) */};
static asn_per_constraints_t asn_PER_memb_horusReal_constr_5 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 2,  2,  1,  4 }	/* (SIZE(1..4)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_CustomFieldValues_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_CustomFieldValues_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  3 }	/* (0..3) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_horusInt_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_horusInt_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_horusInt_specs_3 = {
	sizeof(struct horusInt),
	offsetof(struct horusInt, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_horusInt_3 = {
	"horusInt",
	"horusInt",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_horusInt_tags_3,
	sizeof(asn_DEF_horusInt_tags_3)
		/sizeof(asn_DEF_horusInt_tags_3[0]) - 1, /* 1 */
	asn_DEF_horusInt_tags_3,	/* Same as above */
	sizeof(asn_DEF_horusInt_tags_3)
		/sizeof(asn_DEF_horusInt_tags_3[0]), /* 2 */
	{ &asn_OER_type_horusInt_constr_3, &asn_PER_type_horusInt_constr_3, SEQUENCE_OF_constraint },
	asn_MBR_horusInt_3,
	1,	/* Single element */
	&asn_SPC_horusInt_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_horusReal_5[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (9 << 2)),
		0,
		&asn_DEF_NativeReal,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_horusReal_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_horusReal_specs_5 = {
	sizeof(struct horusReal),
	offsetof(struct horusReal, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_horusReal_5 = {
	"horusReal",
	"horusReal",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_horusReal_tags_5,
	sizeof(asn_DEF_horusReal_tags_5)
		/sizeof(asn_DEF_horusReal_tags_5[0]) - 1, /* 1 */
	asn_DEF_horusReal_tags_5,	/* Same as above */
	sizeof(asn_DEF_horusReal_tags_5)
		/sizeof(asn_DEF_horusReal_tags_5[0]), /* 2 */
	{ &asn_OER_type_horusReal_constr_5, &asn_PER_type_horusReal_constr_5, SEQUENCE_OF_constraint },
	asn_MBR_horusReal_5,
	1,	/* Single element */
	&asn_SPC_horusReal_specs_5	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_CustomFieldValues_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CustomFieldValues, choice.horusStr),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IA5String,
		0,
		{ &asn_OER_memb_horusStr_constr_2, &asn_PER_memb_horusStr_constr_2,  memb_horusStr_constraint_1 },
		0, 0, /* No default value */
		"horusStr"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CustomFieldValues, choice.horusInt),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_horusInt_3,
		0,
		{ &asn_OER_memb_horusInt_constr_3, &asn_PER_memb_horusInt_constr_3,  memb_horusInt_constraint_1 },
		0, 0, /* No default value */
		"horusInt"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CustomFieldValues, choice.horusReal),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_horusReal_5,
		0,
		{ &asn_OER_memb_horusReal_constr_5, &asn_PER_memb_horusReal_constr_5,  memb_horusReal_constraint_1 },
		0, 0, /* No default value */
		"horusReal"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CustomFieldValues, choice.horusBool),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BitFlags,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"horusBool"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_CustomFieldValues_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* horusStr */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* horusInt */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* horusReal */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* horusBool */
};
asn_CHOICE_specifics_t asn_SPC_CustomFieldValues_specs_1 = {
	sizeof(struct CustomFieldValues),
	offsetof(struct CustomFieldValues, _asn_ctx),
	offsetof(struct CustomFieldValues, present),
	sizeof(((struct CustomFieldValues *)0)->present),
	asn_MAP_CustomFieldValues_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_CustomFieldValues = {
	"CustomFieldValues",
	"CustomFieldValues",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_CustomFieldValues_constr_1, &asn_PER_type_CustomFieldValues_constr_1, CHOICE_constraint },
	asn_MBR_CustomFieldValues_1,
	4,	/* Elements count */
	&asn_SPC_CustomFieldValues_specs_1	/* Additional specs */
};

