/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "HorusBinaryV3"
 * 	found in "../HorusBinaryV3.asn1"
 * 	`asn1c -no-gen-OER -no-gen-example`
 */

#include "GnssPowerSaveState.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
asn_per_constraints_t asn_PER_type_GnssPowerSaveState_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  5 }	/* (0..5) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_GnssPowerSaveState_value2enum_1[] = {
	{ 0,	12,	"psmNotActive" },
	{ 1,	7,	"enabled" },
	{ 2,	11,	"acquisition" },
	{ 3,	8,	"tracking" },
	{ 4,	9,	"optimised" },
	{ 5,	8,	"inactive" }
};
static const unsigned int asn_MAP_GnssPowerSaveState_enum2value_1[] = {
	2,	/* acquisition(2) */
	1,	/* enabled(1) */
	5,	/* inactive(5) */
	4,	/* optimised(4) */
	0,	/* psmNotActive(0) */
	3	/* tracking(3) */
};
const asn_INTEGER_specifics_t asn_SPC_GnssPowerSaveState_specs_1 = {
	asn_MAP_GnssPowerSaveState_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_GnssPowerSaveState_enum2value_1,	/* N => "tag"; sorted by N */
	6,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_GnssPowerSaveState_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_GnssPowerSaveState = {
	"GnssPowerSaveState",
	"GnssPowerSaveState",
	&asn_OP_NativeEnumerated,
	asn_DEF_GnssPowerSaveState_tags_1,
	sizeof(asn_DEF_GnssPowerSaveState_tags_1)
		/sizeof(asn_DEF_GnssPowerSaveState_tags_1[0]), /* 1 */
	asn_DEF_GnssPowerSaveState_tags_1,	/* Same as above */
	sizeof(asn_DEF_GnssPowerSaveState_tags_1)
		/sizeof(asn_DEF_GnssPowerSaveState_tags_1[0]), /* 1 */
	{ 0, &asn_PER_type_GnssPowerSaveState_constr_1, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_GnssPowerSaveState_specs_1	/* Additional specs */
};

