/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "HorusBinaryV3"
 * 	found in "../HorusBinaryV3.asn1"
 * 	`asn1c -no-gen-OER -no-gen-example`
 */

#ifndef	_GnssPowerSaveState_H_
#define	_GnssPowerSaveState_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum GnssPowerSaveState {
	GnssPowerSaveState_psmNotActive	= 0,
	GnssPowerSaveState_enabled	= 1,
	GnssPowerSaveState_acquisition	= 2,
	GnssPowerSaveState_tracking	= 3,
	GnssPowerSaveState_optimised	= 4,
	GnssPowerSaveState_inactive	= 5
} e_GnssPowerSaveState;

/* GnssPowerSaveState */
typedef long	 GnssPowerSaveState_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_GnssPowerSaveState_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_GnssPowerSaveState;
extern const asn_INTEGER_specifics_t asn_SPC_GnssPowerSaveState_specs_1;
asn_struct_free_f GnssPowerSaveState_free;
asn_struct_print_f GnssPowerSaveState_print;
asn_constr_check_f GnssPowerSaveState_constraint;
ber_type_decoder_f GnssPowerSaveState_decode_ber;
der_type_encoder_f GnssPowerSaveState_encode_der;
xer_type_decoder_f GnssPowerSaveState_decode_xer;
xer_type_encoder_f GnssPowerSaveState_encode_xer;
per_type_decoder_f GnssPowerSaveState_decode_uper;
per_type_encoder_f GnssPowerSaveState_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _GnssPowerSaveState_H_ */
#include <asn_internal.h>
