/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "HorusBinaryV3"
 * 	found in "../HorusBinaryV3.asn1"
 * 	`asn1c -no-gen-OER -no-gen-example`
 */

#ifndef	_Telemetry_H_
#define	_Telemetry_H_


#include <asn_application.h>

/* Including external dependencies */
#include <IA5String.h>
#include <NativeInteger.h>
#include "GnssPowerSaveState.h"
#include <OCTET_STRING.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct AdditionalSensors;
struct TemperatureSensors;
struct MilliVoltSensors;

/* Telemetry */
typedef struct Telemetry {
	IA5String_t	 payloadCallsign;
	long	 sequenceNumber;
	long	 timeOfDaySeconds;
	long	 latitude;
	long	 longitude;
	long	 altitudeMeters;
	struct AdditionalSensors	*extraSensors	/* OPTIONAL */;
	long	*velocityHorizontalKilometersPerHour	/* OPTIONAL */;
	long	*gnssSatellitesVisible	/* OPTIONAL */;
	long	*ascentRateCentimetersPerSecond	/* OPTIONAL */;
	long	*pressurehPa	/* OPTIONAL */;
	struct TemperatureSensors	*temperatureCelsius	/* OPTIONAL */;
	long	*humidityPercentage	/* OPTIONAL */;
	struct MilliVoltSensors	*milliVolts	/* OPTIONAL */;
	struct counts {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *counts;
	GnssPowerSaveState_t	*gnssPowerSaveState	/* OPTIONAL */;
	OCTET_STRING_t	*customData	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Telemetry_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Telemetry;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AdditionalSensors.h"
#include "TemperatureSensors.h"
#include "MilliVoltSensors.h"

#endif	/* _Telemetry_H_ */
#include <asn_internal.h>
