/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "HorusBinaryV3"
 * 	found in "../HorusBinaryV3.asn1"
 * 	`asn1c -no-gen-OER -no-gen-example`
 */

#ifndef	_TemperatureSensors_H_
#define	_TemperatureSensors_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TemperatureSensors */
typedef struct TemperatureSensors {
	long	*internal	/* OPTIONAL */;
	long	*external	/* OPTIONAL */;
	long	*custom1	/* OPTIONAL */;
	long	*custom2	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TemperatureSensors_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TemperatureSensors;
extern asn_SEQUENCE_specifics_t asn_SPC_TemperatureSensors_specs_1;
extern asn_TYPE_member_t asn_MBR_TemperatureSensors_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _TemperatureSensors_H_ */
#include <asn_internal.h>
