/*
  FILE....: H_128_384_23.h

  Static arrays for LDPC codec H_128_384_23, generated by ldpc_gen_c_h_file.m.
*/

#define H_128_384_23_NUMBERPARITYBITS 256
#define H_128_384_23_MAX_ROW_WEIGHT 3
#define H_128_384_23_DATA_BYTES       16
#define H_128_384_23_PARITY_BYTES     32
#define H_128_384_23_BITS_PER_PACKET   ((H_128_384_23_DATA_BYTES + H_128_384_23_PARITY_BYTES) * 8)
#define H_128_384_23_CODELENGTH 384
#define H_128_384_23_NUMBERROWSHCOLS 128
#define H_128_384_23_MAX_COL_WEIGHT 5
#define H_128_384_23_DEC_TYPE 0
#define H_128_384_23_MAX_ITER 100
#define H_128_384_23_COPRIME 383

extern const uint16_t H_128_384_23_H_rows[];
extern const uint16_t H_128_384_23_H_cols[];
extern const float H_128_384_23_input[];
extern const char H_128_384_23_detected_data[];

